# Generated by Django 6.0.7 on 2026-07-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='interests',
            field=models.CharField(blank=True, choices=[('AI', 'Artificial Intelligence'), ('TECH', 'Technology'), ('SPORTS', 'Sports'), ('BUSINESS', 'Business'), ('HEALTH', 'Health'), ('EDUCATION', 'Education'), ('ENTERTAINMENT', 'Entertainment'), ('POLITICS', 'Politics'), ('SCIENCE', 'Science'), ('ENVIRONMENT', 'Environment'), ('TRAVEL', 'Travel')], max_length=100, null=True),
        ),
    ]
